### ISSUE TITLE
SAME CLI does not install

### ISSUE THREAD

**Issue by timbuktuu** [SAME-Project/SAMPLE-CLI-TESTER#1] opened 2021-04-04 00:50 UTC
#### Issue description

Could not install CLI on M1 (ARM) osx machine.

#### Steps to reproduce the issue

1.  curl -L0 https://get.sameproject.org/ | bash 

#### What's the expected result?

- CLI installed

#### What's the actual result?

-SAME CLI does does not install.

#### Additional details / screenshot

`% curl -L0 https://get.sameproject.org/ | bash -
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 Dload  Upload   Total   Spent    Left  Speed
100  7633  100  7633    0     0  13025      0 --:--:-- --:--:-- --:--:-- 13025
Your system is darwin_amd64
No SAME detected. Installing fresh SAME CLI...
Getting the latest SAME CLI...
Installing 0.0.43 SAME CLI...
/var/folders/_2/2ngt27g95b18mtj13m1spr5c0000gn/T/same-install-XXXXXX.HIOxGZPC
Downloading https://github.com/SAME-Project/SAMPLE-CLI-TESTER/releases/download/0.0.43/same_0.0.43_darwin_amd64.tar.gz ...
Downloading sig file https://github.com/SAME-Project/SAMPLE-CLI-TESTER/releases/download/0.0.43/same_0.0.43_darwin_amd64.tar.gz.signature.sha256 ...
Error reading signature file /var/folders/_2/2ngt27g95b18mtj13m1spr5c0000gn/T/same-install-XXXXXX.HIOxGZPC/same_0.0.43_darwin_amd64.tar.gz.signature.sha256.decoded
Failed to verify signature of tarball.
Failed to install SAME CLI`

**Comment by aronchick** [comment] 2021-04-04 12:45
I suspect this is due to missing functionality on Mac. Can you try to download the binary directly from the release tag and run it?


________________________________
From: Tim Kelton ***@***.***>
Sent: Saturday, April 3, 2021 5:50:23 PM
To: SAME-Project/SAMPLE-CLI-TESTER ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SAME-Project/SAMPLE-CLI-TESTER] SAME CLI does not install (#1)


Issue description

Could not install CLI on M1 (ARM) osx machine.

Steps to reproduce the issue

  1.  curl -L0 https://get.sameproject.org/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fget.sameproject.org%2F&data=04%7C01%7Cdavid.aronchick%40microsoft.com%7C29011879a8e842d335c708d8f703a168%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637530942255421896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hM0raA6KAkyYSSQcja3y7C3REGsT1Jp%2FRM1TZoQmGEQ%3D&reserved=0> | bash

What's the expected result?

  *   CLI installed

What's the actual result?

-SAME CLI does does not install.

Additional details / screenshot

% curl -L0 https://get.sameproject.org/ | bash - % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 7633 100 7633 0 0 13025 0 --:--:-- --:--:-- --:--:-- 13025 Your system is darwin_amd64 No SAME detected. Installing fresh SAME CLI... Getting the latest SAME CLI... Installing 0.0.43 SAME CLI... /var/folders/_2/2ngt27g95b18mtj13m1spr5c0000gn/T/same-install-XXXXXX.HIOxGZPC Downloading https://github.com/SAME-Project/SAMPLE-CLI-TESTER/releases/download/0.0.43/same_0.0.43_darwin_amd64.tar.gz ... Downloading sig file https://github.com/SAME-Project/SAMPLE-CLI-TESTER/releases/download/0.0.43/same_0.0.43_darwin_amd64.tar.gz.signature.sha256 ... Error reading signature file /var/folders/_2/2ngt27g95b18mtj13m1spr5c0000gn/T/same-install-XXXXXX.HIOxGZPC/same_0.0.43_darwin_amd64.tar.gz.signature.sha256.decoded Failed to verify signature of tarball. Failed to install SAME CLI

**Comment by aronchick** [comment] 2021-04-04 12:49
Oh never mind - we’re not even doing Darwin builds right now. Can you try to build manually?


________________________________

**Comment by aronchick** [comment] 2021-04-04 16:56
This is weird - I'm not sure how you even got here because it should have failed with a download error :)

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7633  100  7633    0     0  66956      0 --:--:-- --:--:-- --:--:-- 66956
No prebuilt binary for darwin-arm64
Failed to install SAME CLI
For support, go to https://github.com/SAME-Project/SAMPLE-CLI-TESTER
```

Can you run the two following commands?

```
uname -m
echo `uname`|tr '[:upper:]' '[:lower:]'
```

**Comment by aronchick** [comment] 2021-04-04 19:41
K - was able to repro, working on it today.

In the interim, you can/should be able to just fork the repo and `make build` and it SHOULD work.

**Comment by aronchick** [comment] 2021-04-04 22:24
K - problem fixed on my local machine. Please reopen if still broken.

**Closed as completed by aronchick** 2021-04-04 22:24 UTC
